"""Thin CLI helpers. Prefer domain modules as entrypoints:

  python -m narrator_pipeline.analysis.step0 ...
  python -m narrator_pipeline.analysis.step1 ...
  python -m narrator_pipeline.audio.step2 ...
  python -m narrator_pipeline.images.step3 ...
  python -m narrator_pipeline.codegen.step4 ...
  python -m narrator_pipeline.cli.validate_scene_scripts ...
"""
